# Generated by Django 5.0.1 on 2025-10-06 21:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del dispositivo', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo del dispositivo', max_length=200, verbose_name='nombre')),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuador'), ('gateway', 'Gateway'), ('controller', 'Controlador'), ('other', 'Otro')], default='sensor', help_text='Tipo de dispositivo IoT', max_length=20, verbose_name='tipo de dispositivo')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del dispositivo', null=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dispositivo está activo en la plataforma', verbose_name='activo')),
                ('status', models.CharField(choices=[('online', 'En línea'), ('offline', 'Fuera de línea'), ('error', 'Error'), ('maintenance', 'Mantenimiento')], default='offline', help_text='Estado actual del dispositivo', max_length=20, verbose_name='estado')),
                ('last_connection', models.DateTimeField(blank=True, help_text='Última vez que el dispositivo se conectó', null=True, verbose_name='última conexión')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del dispositivo en formato JSON', verbose_name='metadatos')),
                ('location', models.CharField(blank=True, help_text='Ubicación física del dispositivo', max_length=200, null=True, verbose_name='ubicación')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud de la ubicación', max_digits=9, null=True, verbose_name='latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud de la ubicación', max_digits=9, null=True, verbose_name='longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('owner', models.ForeignKey(help_text='Usuario propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'dispositivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del comando', primary_key=True, serialize=False)),
                ('command_type', models.CharField(help_text='Tipo o nombre del comando (ej: set_temperature, restart, update_config)', max_length=100, verbose_name='tipo de comando')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos del comando en formato JSON', verbose_name='payload')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('executed', 'Ejecutado'), ('failed', 'Fallido'), ('timeout', 'Timeout')], default='pending', help_text='Estado actual del comando', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se creó el comando', verbose_name='creado en')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Momento en que se envió el comando al dispositivo', null=True, verbose_name='enviado en')),
                ('executed_at', models.DateTimeField(blank=True, help_text='Momento en que el dispositivo ejecutó el comando', null=True, verbose_name='ejecutado en')),
                ('response', models.JSONField(blank=True, help_text='Respuesta del dispositivo en formato JSON', null=True, verbose_name='respuesta')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el comando', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('device', models.ForeignKey(help_text='Dispositivo destino del comando', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='iot_core.device', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'comando',
                'verbose_name_plural': 'comandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('rule_type', models.CharField(choices=[('threshold', 'Umbral'), ('range', 'Rango'), ('change', 'Cambio'), ('offline', 'Dispositivo Offline')], default='threshold', max_length=20, verbose_name='tipo de regla')),
                ('condition', models.JSONField(help_text='Condición de la alerta en formato JSON', verbose_name='condición')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='severidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('notify_email', models.BooleanField(default=False, verbose_name='notificar por email')),
                ('notify_webhook', models.URLField(blank=True, null=True, verbose_name='webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='última activación')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='iot_core.device', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Momento en que se generó la telemetría', verbose_name='timestamp')),
                ('data', models.JSONField(help_text='Datos de telemetría en formato JSON (ej: {"temperatura": 25.3, "humedad": 60})', verbose_name='datos')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se recibió la telemetría en el servidor', verbose_name='recibido en')),
                ('device', models.ForeignKey(help_text='Dispositivo que envió la telemetría', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='iot_core.device', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'telemetría',
                'verbose_name_plural': 'telemetrías',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['owner', 'is_active'], name='iot_core_de_owner_i_0f125e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='iot_core_de_device__2764e4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='iot_core_de_status_a6f4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-last_connection'], name='iot_core_de_last_co_3e2721_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['device', '-created_at'], name='iot_core_co_device__f112f3_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status'], name='iot_core_co_status_496d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['-created_at'], name='iot_core_co_created_fc1461_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', 'is_active'], name='iot_core_al_device__cf637b_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['device', '-timestamp'], name='iot_core_te_device__09de89_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['-timestamp'], name='iot_core_te_timesta_9f6946_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['-received_at'], name='iot_core_te_receive_3e161f_idx'),
        ),
    ]
